### ISSUE TITLE
Error: Unmatched closing tag: EventNotificationAlert

### ISSUE THREAD

**Issue by ozett** [henry-spanka/node-red-contrib-hikvision#20]
is this a bug in my nodes?
or a bug within your scriptcode?

can i dig into it?

```
4 Dec 11:54:03 - [red] Uncaught Exception:
4 Dec 11:54:03 - Error: Unmatched closing tag: EventNotificationAlert
Line: 2
Column: 25
Char: >
    at error (/root/.node-red/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/root/.node-red/node_modules/sax/lib/sax.js:693:7)
    at closeTag (/root/.node-red/node_modules/sax/lib/sax.js:895:7)
    at SAXParser.write (/root/.node-red/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/root/.node-red/node_modules/node-hikvision-api/node_modules/xml2js/lib/parser.js:325:31)
    at Parser.parseString (/root/.node-red/node_modules/node-hikvision-api/node_modules/xml2js/lib/parser.js:5:59)
    at Hikvision.handleData (/root/.node-red/node_modules/node-hikvision-api/Hikvision.js:187:16)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
root@deb8mpd-virt:~/.node-red#
```
![image](https://user-images.githubusercontent.com/5937811/70138306-46f84980-1690-11ea-8bda-0d243ca124a6.png)

**Comment by henry-spanka** [comment]
Uhm. I never encountered it. Basically your camera sent invalid data which caused the plugin to crash. We can add a check to discard invalid data but not sure if it helps.

**Comment by ozett** [comment]
maybe log (or to special file for later investigation) and than discard for stablity....
🤔
